Accepted scientific work
WyimaginowaneKoniki/Kongres pull request #14
Opened 2020-11-29 13:10 UTC by Kwolik

- Create page accepted scientific work
- Create file AcceptedScientificWorkComponents.jsx
- Setting of all items
- View for the person not logged in

![obraz](https://user-images.githubusercontent.com/44361068/100542755-559a2200-324c-11eb-86d4-56c8afc9c394.png)

2020-11-29 18:13 UTC, KamilDonda approved these changes

2020-11-30 18:24 UTC, JustD4nTe approved these changes

2020-11-30 21:05 UTC, upsu90 requested changes

2020-11-30 21:05 UTC, upsu90 commented on web-client/src/components/AcceptedScientificWorkComponents.jsx
> +                <h2 className={style.h2}>{props.title}</h2>
h1 imo (we should use h1 if it's page title)

2020-12-01 23:58 UTC, upsu90 approved these changes

2020-12-02 08:49 UTC, merged