Register reviewer/participant: website => api => db
WyimaginowaneKoniki/Kongres pull request #21
Opened 2020-12-30 14:35 UTC by JustD4nTe

- Create endpoints for reviewer and participant to login and register
- Write participant avatar on server
- After successful register move to main page

2020-12-30 19:16 UTC, Kwolik requested changes

2020-12-30 19:16 UTC, Kwolik commented on web-client/src/components/SignUpForm.jsx
> +  const formRef = React.useRef(null);
We don't do that anymore? 
We just define (React.useRef) at the beginning

2020-12-30 19:50 UTC, Kwolik approved these changes

2020-12-31 11:56 UTC, KamilDonda approved these changes

2021-01-02 20:13 UTC, upsu90 requested changes
I found a bug: after adding a photo and pressing "Sign up" nothing happens (even after deleting the photo) :c

2021-01-02 20:34 UTC, JustD4nTe commented
> I found a bug: after adding a photo and pressing "Sign up" nothing happens (even after deleting the photo) :c
I forgot to include a special folder for files like user's photo :C Last commit should fix this bug

2021-01-02 20:45 UTC, upsu90 approved these changes
everything works!

2021-01-02 20:59 UTC, merged