Create JWT token on logging and store it in LocalStorage
WyimaginowaneKoniki/Kongres pull request #26
Opened 2021-01-06 19:47 UTC by JustD4nTe

2021-01-06 20:31 UTC, Kwolik approved these changes

2021-01-07 11:20 UTC, KamilDonda commented on web-client/src/pages/signin-participant.js
> +          window.location.href = "https://localhost:5001";
I think it's better to assign `"https://localhost:5001"` in const.

2021-01-07 11:22 UTC, KamilDonda commented on web-client/src/pages/signin-reviewer.js
> +          window.location.href = "https://localhost:5001";
Same as in SignIn-Participant

2021-01-07 20:01 UTC, upsu90 requested changes
great! but... after signing in I saw the error message about invalid password and then I successfully signed in

2021-01-08 16:25 UTC, KamilDonda approved these changes

2021-01-08 19:55 UTC, upsu90 approved these changes

2021-01-08 19:55 UTC, merged