My profile
WyimaginowaneKoniki/Kongres pull request #27
Opened 2021-01-07 13:59 UTC by Kwolik

2021-01-07 21:19 UTC, upsu90 requested changes

2021-01-07 21:19 UTC, upsu90 commented on web-client/src/components/ChangePassword.jsx
> +    // },
@JustD4nTe will be angry :c

2021-01-07 21:19 UTC, upsu90 commented on web-client/src/components/PersonalInformation.jsx
> +            : null}
we don't need acceptance again

2021-01-08 20:07 UTC, upsu90 requested changes

2021-01-08 20:07 UTC, upsu90 commented on web-client/src/components/PersonalInformation.jsx
> +              {!props.firstName && !props.lastName && !props.email ? "Sign up" : "Save changes"}
Do we need "Sign up" here?

2021-01-08 22:21 UTC, upsu90 approved these changes

2021-01-09 10:43 UTC, KamilDonda approved these changes

2021-01-09 10:46 UTC, JustD4nTe approved these changes

2021-01-09 10:46 UTC, JustD4nTe commented on web-client/src/components/ChangePassword.jsx
> +  });
Pointless comments

2021-01-09 10:46 UTC, JustD4nTe commented on web-client/src/components/ChangePassword.jsx
> +  });
adn here too

2021-01-09 11:07 UTC, merged