Selects
WyimaginowaneKoniki/Kongres pull request #29
Opened 2021-01-09 21:27 UTC by Kwolik

Repair all selects and footer in adding work

2021-01-10 12:55 UTC, upsu90 requested changes
placeholder should contain "Select"

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/components/PersonalInformation.jsx
> +              autoComplete="job-title"
it isn't an academic title or job title so please change id and autoComplete

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/components/PersonalInformation.jsx
> +                Psychics               
please change to Physics

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/components/SignUpForm.jsx
> +                Psychics               
Physics :p

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/components/SignUpForm.jsx
> +              autoComplete="job-title"
id and autoComplete again

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/pages/adding-work.js
> +      then: yup.string().required("Time field is required"),
why "Time field"?

2021-01-10 12:55 UTC, upsu90 commented on web-client/src/pages/adding-work.js
> +                Psychics               
Physics

2021-01-12 09:23 UTC, KamilDonda reviewed
+ ![image](https://user-images.githubusercontent.com/44376350/104292853-9fb62a80-54bd-11eb-8c33-a6ec8823a5d5.png)

+ when I choose "Select" I don't get an error: 
![image](https://user-images.githubusercontent.com/44376350/104294927-1eac6280-54c0-11eb-8d6d-3b2ac8136f14.png)

2021-01-13 21:41 UTC, KamilDonda approved these changes

2021-01-14 21:54 UTC, upsu90 approved these changes

2021-01-15 11:06 UTC, JustD4nTe approved these changes

2021-01-15 13:04 UTC, merged