Get data from API to single scientific work page
WyimaginowaneKoniki/Kongres pull request #31
Opened 2021-01-14 13:12 UTC by JustD4nTe

- Handle adding reviews/answers to review
- Get data to display information about work (with reviews and answers)
- Add ability to download review (only when reviewer upload it as file)
- Refactor components in the page:
  - Rename components
  - Implement using flex display (almost in all components on the page)
- Separate reviews for users:
  - normal user cannot see reviews
  - reviewer can see only own reviews and answers to it
  - author of work can see all reviews

2021-01-14 16:53 UTC, KamilDonda approved these changes

2021-01-14 22:49 UTC, upsu90 requested changes
when an author doesn't have a photo, I have an error

2021-01-15 10:24 UTC, Kwolik requested changes
- Download full work after entering a specific job, it does not work,
- A reviewer, when he is not assigned to any work, cannot view it

2021-01-15 12:43 UTC, Kwolik requested changes

2021-01-15 12:43 UTC, Kwolik commented on Kongres.Api/Kongres.Api.Application/Services/ReviewService.cs
> +                review.Comment = reviewMsg;
The assumption was that both versions of the review could be added.

2021-01-15 16:27 UTC, Kwolik approved these changes
Finally. Good job

2021-01-15 20:52 UTC, upsu90 requested changes
We should also be able to add other characters :c 
![image](https://user-images.githubusercontent.com/44305068/104776207-010a2200-577a-11eb-9a47-d1894e7941d5.png)

2021-01-15 21:50 UTC, upsu90 approved these changes

2021-01-15 21:54 UTC, merged