Protected react router
WyimaginowaneKoniki/Kongres pull request #32
Opened 2021-01-15 20:53 UTC by Kwolik

- Creating headers for individual users
- Blocking websites for unwanted people
- Create page 404
- Blocking non-existent pages

2021-01-15 21:03 UTC, JustD4nTe approved these changes

2021-01-15 21:37 UTC, upsu90 approved these changes

2021-01-15 21:37 UTC, upsu90 commented on web-client/src/components/Navigation.jsx
> +      marginTop: "10.5px",
we don't use .5px but I'll change it later :c

2021-01-16 10:37 UTC, KamilDonda commented on web-client/src/components/Navigation.jsx
> +            <NavLink exact to="/work-view">
It should contain id of work, e.g:
`/work-view/1`

2021-01-16 10:44 UTC, KamilDonda requested changes
+ In my profile, reviewer can change his photo, but he doesn't have a photo.
+ When I am a reviewer and I click "My reviews",  I got redirected to Sign In (Reviewer).

2021-01-17 12:47 UTC, KamilDonda approved these changes

2021-01-17 12:48 UTC, merged