Email service
WyimaginowaneKoniki/Kongres pull request #33
Opened 2021-01-17 14:42 UTC by KamilDonda

+ Send confirm email after register as Participant
+ Add two columns in database

2021-01-17 16:29 UTC, Kwolik approved these changes

2021-01-17 18:05 UTC, JustD4nTe requested changes

2021-01-17 18:05 UTC, JustD4nTe commented on Kongres.Api/Kongres.Api.WebApi/appsettings.json
> +    "SenderEmail": "no-reply@Scienture.com"
noreply@Scienture.com

2021-01-17 18:08 UTC, JustD4nTe approved these changes

2021-01-18 10:36 UTC, upsu90 approved these changes

2021-01-18 10:36 UTC, upsu90 commented on Kongres.Api/Kongres.Api.WebApi/appsettings.json
> +    "SenderEmail": "noreply@Scienture.com"
please change name to "Scienture conference" and mail to "noreply@scientureconf.com"

2021-01-18 11:12 UTC, merged