Agenda
WyimaginowaneKoniki/Kongres pull request #4
Opened 2020-11-19 22:24 UTC by KamilDonda

- Add Material UI to project
- Create component: agendaEvent.js
- Update agenda.js (add mentioned above component)

2020-11-20 12:55 UTC, JustD4nTe requested changes
Looks okay, but you should add more examples in single day (adding other day with events will be great too)

2020-11-20 15:49 UTC, upsu90 approved these changes
Imo it's ok :)

2020-11-20 15:58 UTC, Kwolik approved these changes
maybe ok?

2020-11-21 13:05 UTC, JustD4nTe approved these changes

2020-11-21 13:07 UTC, merged