create page about
WyimaginowaneKoniki/Kongres pull request #9
Opened 2020-11-24 20:40 UTC by Kwolik

2020-11-24 21:02 UTC, KamilDonda commented
- Components should have .jsx extension.
- Please, add more space at the bottom of the page. [pic]
![pic](https://user-images.githubusercontent.com/44376350/100150274-b073f800-2e9f-11eb-88d5-93ada2944190.png)

- I think, the better idea is to add 4 AboutProfil component than 2 AboutProfil (1 component = 1 person, not 1 component = 2 persones).
![pic](https://user-images.githubusercontent.com/44376350/100150860-9dadf300-2ea0-11eb-970a-1bd30274273e.png)

2020-11-25 16:22 UTC, KamilDonda approved these changes

2020-11-25 17:45 UTC, JustD4nTe requested changes

2020-11-25 17:45 UTC, JustD4nTe commented on web-client/src/components/AboutInfo.jsx
> +
Unwanted enter

2020-11-25 17:45 UTC, JustD4nTe commented on web-client/src/pages/about.js
> +    isImageRight: false,
By default, variables returns false in boolean expressions

2020-11-25 17:45 UTC, JustD4nTe commented on web-client/src/components/AboutInfo.jsx
> +    if(props.isImageRight === true)
You don't have to compare isImageRight to true (it will still be working properly) or am I missing something?

2020-11-25 17:54 UTC, upsu90 requested changes

2020-11-25 17:54 UTC, upsu90 commented on web-client/src/components/AboutInfo.jsx
> +                    <h5>{props.head}</h5>
it should be h2 imo

2020-11-25 17:54 UTC, upsu90 commented on web-client/src/components/AboutInfo.jsx
> +            textAlign: 'justify',
never justify text on the page :c (it'll be difficult to read)

2020-11-25 17:54 UTC, upsu90 commented on web-client/src/components/AboutInfo.jsx
> +            fontSize: '105%',
please use pixels to set font size

2020-11-25 17:54 UTC, upsu90 commented on web-client/src/pages/about.js
> +    link: "/reviewers",
link to regulations

2020-11-25 18:22 UTC, JustD4nTe approved these changes

2020-11-25 18:31 UTC, upsu90 approved these changes
ok:)

2020-11-25 18:51 UTC, merged